language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
cache: yarn
deploy:
  provider: pages:git
  edge: true # opt in to dpl v2
  token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，添加为环境变量
  target_branch: gh-pages
  keep_history: true
  commit_message: Deploy %{project_name} to %{url}:%{target_branch}
  local_dir: docs-dist # Directory to push to GitHub Pages
  project_name: DingTalk # Used in the commit message only (defaults to fqdn or the current repo slug)
  deployment_file: true # Enable creation of a deployment-info file 
  skip_cleanup: true # Make sure you have skip_cleanup set to true, otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
  on:
    branch: master